name: Deploy-phase
on: push
jobs:
  Deploy-phase:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run test
        run: npm run test
      - name: Lint
        run: npm run lint
      - name: Deploy project
        run: echo "Deploying project..."
      
